// Code generated by sqlc. DO NOT EDIT.
// source: asset.sql

package db

import (
	"context"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO "Assets" (
  internal_id,
  asset_name,
  asset_created_at
) VALUES (
  $1, $2, $3
)
RETURNING id, internal_id, asset_name, asset_created_at, created_at
`

type CreateAssetParams struct {
	InternalID     int64  `json:"internal_id"`
	AssetName      string `json:"asset_name"`
	AssetCreatedAt string `json:"asset_created_at"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, createAsset, arg.InternalID, arg.AssetName, arg.AssetCreatedAt)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.InternalID,
		&i.AssetName,
		&i.AssetCreatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAsset = `-- name: DeleteAsset :exec
DELETE FROM "Assets"
WHERE id = $1
`

func (q *Queries) DeleteAsset(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAsset, id)
	return err
}

const getAsset = `-- name: GetAsset :one
SELECT id, internal_id, asset_name, asset_created_at, created_at FROM "Assets"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAsset(ctx context.Context, id int64) (Asset, error) {
	row := q.db.QueryRowContext(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.InternalID,
		&i.AssetName,
		&i.AssetCreatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, internal_id, asset_name, asset_created_at, created_at FROM "Assets"
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListAssetsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAssets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.InternalID,
			&i.AssetName,
			&i.AssetCreatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
