// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Asset struct {
	ID             int64     `json:"id"`
	InternalID     int64     `json:"internal_id"`
	AssetName      string    `json:"asset_name"`
	AssetCreatedAt string    `json:"asset_created_at"`
	Status         bool      `json:"status"`
	AssetLink      string    `json:"asset_link"`
	CreatedAt      time.Time `json:"created_at"`
}
